eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8090/eureka/}
# okta:
#  oauth2:
#    issuer: https://dev-36467488.okta.com/oauth2/default
#    audience: api://default
# spring:
#   zipkin:
#     baseUrl: http://zipkin-svc:9411

management:
  tracing:
    export:
      zipkin:
        base-url: http://zipkin-svc:9411
