eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8090/eureka/}
# okta:
#  oauth2:
#    issuer: https://dev-36467488.okta.com/oauth2/default
#    audience: api://default
# spring:
#   zipkin:
#     baseUrl: http://zipkin-svc:9411

management:
  tracing:
    sampling:
      probability: 1.0  # Set to 1.0 for testing (100% sampling); lower (e.g., 0.1) in production
  zipkin:
    tracing:
      endpoint: http://zipkin-svc:9411/api/v2/spans  # Full endpoint URL (critical!)
